// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_o5EZwViXTvUtO1ZCAkj9xJ7k7GYoCOY',
    appId: '1:251249557153:web:a436c9dfca3f92dd663ae0',
    messagingSenderId: '251249557153',
    projectId: 'gardencity-25df6',
    authDomain: 'gardencity-25df6.firebaseapp.com',
    storageBucket: 'gardencity-25df6.firebasestorage.app',
    measurementId: 'G-HQDJJ605S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVeUM1zVJIFyQ1otMmvlL66ESga2YS2Y',
    appId: '1:251249557153:android:e66358a493ff0bb3663ae0',
    messagingSenderId: '251249557153',
    projectId: 'gardencity-25df6',
    storageBucket: 'gardencity-25df6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzaS9-lPFh4rPVWE7k5OUFfAsqDJ-uCI0',
    appId: '1:251249557153:ios:056542bc94c86e3a663ae0',
    messagingSenderId: '251249557153',
    projectId: 'gardencity-25df6',
    storageBucket: 'gardencity-25df6.firebasestorage.app',
    iosBundleId: 'com.example.gardencity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzaS9-lPFh4rPVWE7k5OUFfAsqDJ-uCI0',
    appId: '1:251249557153:ios:056542bc94c86e3a663ae0',
    messagingSenderId: '251249557153',
    projectId: 'gardencity-25df6',
    storageBucket: 'gardencity-25df6.firebasestorage.app',
    iosBundleId: 'com.example.gardencity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_o5EZwViXTvUtO1ZCAkj9xJ7k7GYoCOY',
    appId: '1:251249557153:web:bea804186415804f663ae0',
    messagingSenderId: '251249557153',
    projectId: 'gardencity-25df6',
    authDomain: 'gardencity-25df6.firebaseapp.com',
    storageBucket: 'gardencity-25df6.firebasestorage.app',
    measurementId: 'G-BPVEZP14F8',
  );

}